# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: L'Oasis
email: your-email@example.com
contact:
  name: L'Oasis
  address1: Rue Soeur Jean Gabriel
  address2: 24460 Château-L'Évêque
  phone: "05 53 54 30 71"
baseurl: ""
url: "https://oasis-24750.netlify.com/"
permalink: :year/:month/:title/
locale: fr_FR
defaults:
  - scope:
      path: ""
    values:
      lang: fr
      locale: fr_FR
      base-url: "/"
  - scope:
      path: "/en"
    values:
      locale: "en_US"
      base-url: "/en/"

# Images RWD
cloudinary:
  cloud_name: oasis-st-vincent

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
