backend:
  name: github
  repo: DaughtersOfCharity/oasis
  branch: master
publish_mode: editorial_workflow
media_folder: "images"
public_folder: "/images"
collections:
  - name: "pages_fr"
    label: "Pages FR"
    description: >
      Pages en français du site
    files:
      - name: "index"
        label: "Accueil"
        file: "index.html"
        delete: false
        fields:
          - {label: "Gabarit", name: "layout", widget: "hidden", default: "default"}
          - {label: "Titre", name: "title", widget: "hidden", default: "Bienvenue"}
          - {label: "I18n", name: "i18n-key", widget: "hidden", default: "home"}
          - {label: "Contenu", name: "body", widget: text}
      - name: "infos"
        label: "Informations pratiques"
        file: "infos.html"
        delete: false
        fields:
          - {label: "Gabarit", name: "layout", widget: "hidden", default: "default"}
          - {label: "Titre", name: "title", widget: "hidden", default: "Informations pratiques"}
          - {label: "I18n", name: "i18n-key", widget: "hidden", default: "about"}
          - {label: "Contenu", name: "body", widget: text}
      - name: "tarifs"
        label: "Tarifs et réservation"
        file: "tarifs.html"
        delete: false
        fields:
          - {label: "Gabarit", name: "layout", widget: "hidden", default: "default"}
          - {label: "Titre", name: "title", widget: "hidden", default: "Tarifs et réservation"}
          - {label: "I18n", name: "i18n-key", widget: "hidden", default: "booking"}
          - {label: "Contenu", name: "body", widget: text}
      - name: "a-proximite"
        label: "À proximité de l'Oasis"
        file: "a-proximite.html"
        delete: false
        fields:
          - {label: "Gabarit", name: "layout", widget: "hidden", default: "default"}
          - {label: "Titre", name: "title", widget: "hidden", default: "À proximité de l'Oasis"}
          - {label: "I18n", name: "i18n-key", widget: "hidden", default: "nearby"}
          - {label: "Contenu", name: "body", widget: text}
  - name: "pages_en"
    label: "Pages EN"
    description: >
      Pages en anglais du site
    files:
      - name: "index"
        label: "Welcome"
        file: "en/index.html"
        delete: false
        fields:
          - {label: "Gabarit", name: "layout", widget: "hidden", default: "default"}
          - {label: "Titre", name: "title", widget: "hidden", default: "Welcome"}
          - {label: "I18n", name: "i18n-key", widget: "hidden", default: "home"}
          - {label: "Contenu", name: "body", widget: text}
      - name: "about"
        label: "About us"
        file: "en/about.html"
        delete: false
        fields:
          - {label: "Gabarit", name: "layout", widget: "hidden", default: "default"}
          - {label: "Titre", name: "title", widget: "hidden", default: "About us"}
          - {label: "I18n", name: "i18n-key", widget: "hidden", default: "about"}
          - {label: "Contenu", name: "body", widget: text}
      - name: "booking"
        label: "Prices and Booking"
        file: "en/booking.html"
        delete: false
        fields:
          - {label: "Gabarit", name: "layout", widget: "hidden", default: "default"}
          - {label: "Titre", name: "title", widget: "hidden", default: "Prices and Booking"}
          - {label: "I18n", name: "i18n-key", widget: "hidden", default: "booking"}
          - {label: "Contenu", name: "body", widget: text}
      - name: "nearby"
        label: "Nearby the Oasis"
        file: "en/nearby.html"
        delete: false
        fields:
          - {label: "Gabarit", name: "layout", widget: "hidden", default: "default"}
          - {label: "Titre", name: "title", widget: "hidden", default: "Nearby the Oasis"}
          - {label: "I18n", name: "i18n-key", widget: "hidden", default: "nearby"}
          - {label: "Contenu", name: "body", widget: text}